### ISSUE TITLE
Departed Terrance changed more similiar to Cloister Prime

### ISSUE THREAD

**Issue by Omega4200** [Crowns-of-Power/CoP#9]
DT bosses are on a 36hour timer best guild normally hoggs the bosses "what choice did i have :)" I think if it were spawn base bosses like CLoister prime would give others better chances. Maybe if we did that we wouldnt have a reason to play some Aggro wars that we all hated from back in the day. I would look into how hard/easy it is to spawn the CP bosses..... maybe make it a tiny bit harder to spawn the dt bosses

**Comment by allanon-pilgrim** [comment]
I like this, it would open it up for more people/groups. May still need a minimum respawn timer (maybe 2-3 hours) on top of the % spawn chance. Drop rates would probably also have to be reduced.

Question : 
Would it need to be possible to bypass some bosses?  Atm you kinda have to do them in order (yes I know you can run past them, using Bind Soul). CP you only enter the rooms you want to kill the bosses in. This could be done just by changing the position of boss/PH.
